
services:
  postgres:
    build: ./docker/postgres
    container_name: docker-postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./SQL:/home/user/SQL
      - ./SQL/demo.sql:/docker-entrypoint-initdb.d/02-demo.sql:ro
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: demo
      BIODB_DB_NAME_EXAMPLE: demo


volumes:
  pgdata:


