
services:
  postgres:
    build: ./docker/postgres
    container_name: docker-postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./SQL:/home/user/SQL
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      # POSTGRES_DB を指定しないため、デフォルトの postgres DB のみ作成
      # 演習用なので user はスーパーユーザ相当の全権限を持つ


volumes:
  pgdata:


